global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Мониторинг самого Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Мониторинг Spring Boot приложения
  - job_name: 'hhparser-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['hhparser-app:9595']
    scrape_interval: 30s

  # Мониторинг PostgreSQL (если установлен postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  # Мониторинг Nginx (если установлен nginx-prometheus-exporter)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    scrape_interval: 30s
